CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, username TEXT NOT NULL, password TEXT NOT NULL);

CREATE TABLE test (id INT AUTO_INCREMENT PRIMARY KEY, username TEXT NOT NULL, text TEXT NOT NULL, time TIMESTAMP DEFAULT CURRENT_TIMESTAMP + INTERVAL 5 HOUR + INTERVAL 30 MINUTE);