CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL);

CREATE TABLE test (id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(255) NOT NULL, text VARCHAR(255) NOT NULL, time TIMESTAMP DEFAULT CURRENT_TIMESTAMP + INTERVAL 5 HOUR + INTERVAL 30 MINUTE);

CREATE TABLE feedback (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, username VARCHAR(255), feedback TEXT, time TIMESTAMP DEFAULT CURRENT_TIMESTAMP + INTERVAL 5 HOUR + INTERVAL 30 MINUTE);